#!/bin/bash

set -ex

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

mv dvb-docker docker-compose.yml /home/sparklyballs/

sudo useradd -u 99 -g 100 -d /config -s /bin/false tvheadend
sudo usermod -G video tvheadend

sudo mkdir -p \
/config \
/recordings \
/timeshift

sudo chown -R \
/config \
/recordings \
/timeshift

sudo apt-get update
sudo apt-get install -y \
curl \
git \
python-dev \
python-pip \
unrar \
unzip \
wget

[[ -e /tmp/firmware ]] && rm -rf /tmp/firmware
[[ -e /tmp/firmare-src.zip ]] && rm -rf /tmp/firmare-src.zip
curl -o /tmp/firmare-src.zip -L http://www.dvbsky.net/download/linux/firmware.zip
unzip /tmp/firmare-src.zip -d /tmp/firmware
cd /tmp/firmware
sudo sh copy-firmware.sh

curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
sudo sh /tmp/get-docker.sh

mkdir -p /home/sparklyballs/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDbhZIzDEzzvkgRRHPKveD5eqS60P0+eWwTcTpoMnzpQ1lT959MIAxcdf1WB/gP22WGXCvqPj73EafAz2vD3o3rllU7aUvz5PZLnwgegJsYsSdoB6y2LUqPYCmoJlCYOFgD8NSB1KMgzZupLQLwK61RVejR+HVEWGE+dQ6LEeefCHSv7jNbpi0HWAbwZ1ToLKHum5rgpzz4VMa3IfHL/R7yeIXh2hnZGDEc0siEqb99looNd2/+eceYgJUF68fDlr9QaZQGhiaBNbg59VwqL91ChxJsx1mFM4UMDG/lpWf9+JaHPYmKYGNp0Qaj6qDFf1ULR3pHKbTdqBLCIL/A1XV3 sparklyballs@gmail.com" > /home/sparklyballs/.ssh/authorized_keys

sudo echo "recordings /recordings 9p trans=virtio,version=9p2000.L,nobootwait,rw,_netdev    0   0" >> /etc/fstab

sudo pip install -U docker-compose
