#!/bin/bash

set -ex

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"


[[ -e /tmp/firmware ]] && rm -rf /tmp/firmware
[[ -e /tmp/firmare-src.zip ]] && rm -rf /tmp/firmare-src.zip

curl -o /tmp/firmare-src.zip -L http://www.dvbsky.net/download/linux/firmware.zip
unzip /tmp/firmare-src.zip -d /tmp/firmware
cd /tmp/firmware
sudo sh copy-firmware.sh

sudo useradd -u 99 -g 100 -d /config -s /bin/false tvheadend
sudo usermod -G video tvheadend

sudo mkdir -p \
/config \
/recordings \
/timeshift

PREV_DIR=$(pwd)

	cd files || exit
	shopt -s globstar nullglob
	for i in *
 	do
	[[ ! -e "/home/sparklyballs/${i}" ]] && cp -prv "${i}" "/home/sparklyballs/${i}"
	done

cd "${PREV_DIR}" || exit

sudo chown -R 99:100 \
/config \
/recordings \
/timeshift

sudo apt-get update
sudo apt-get install -y \
curl \
git \
python-dev \
python-pip \
unrar \
unzip \
wget

curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
sudo sh /tmp/get-docker.sh
sudo pip install -U docker-compose

mkdir -p /home/sparklyballs/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDbhZIzDEzzvkgRRHPKveD5eqS60P0+eWwTcTpoMnzpQ1lT959MIAxcdf1WB/gP22WGXCvqPj73EafAz2vD3o3rllU7aUvz5PZLnwgegJsYsSdoB6y2LUqPYCmoJlCYOFgD8NSB1KMgzZupLQLwK61RVejR+HVEWGE+dQ6LEeefCHSv7jNbpi0HWAbwZ1ToLKHum5rgpzz4VMa3IfHL/R7yeIXh2hnZGDEc0siEqb99looNd2/+eceYgJUF68fDlr9QaZQGhiaBNbg59VwqL91ChxJsx1mFM4UMDG/lpWf9+JaHPYmKYGNp0Qaj6qDFf1ULR3pHKbTdqBLCIL/A1XV3 sparklyballs@gmail.com" > /home/sparklyballs/.ssh/authorized_keys

